name: Alerta de Atividades Validadas

on:
  schedule:
    - cron: '*/15 11-20 * * 1-5' # A cada 15 minutos, horário comercial BRT
  workflow_dispatch:

jobs:
  alerta-validado:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: |
          pip install -r requirements.txt

      - name: Executar alerta de atividades validadas
        env:
          AZURE_PAT: ${{ secrets.AZURE_PAT }}
          HOMOLOGACAO_WEBHOOK_URL: ${{ secrets.HOMOLOGACAO_WEBHOOK_URL }}
        run: python alerta_validado.py